### PR TITLE
Add more metrics (movement, fan speed...)

### PR DESCRIPTION
**Pull request by deadly667**
I took parts from https://github.com/sbelectronics/octoprint-prometheus and added to this repo because I like it more. 

Metrics added:
- print total time
- last print time
- movement of axis (x, y, z, e and speed)
- fan speed
- extrusion total 
- last print extrusion

### CODE REVIEW

**Comment by tg44** [comment]
Yeah... My problem with these metrics; some of them have no added value. Or at least the movements, if they are not a sum value to the whole print are just totally misaligned. For those, we would need an event db, or we can just simply check it in the gcode viewer :D 

The fan speed and extrusion total are nice!
Print total time and last print time could also be helpful.

If you can remove the x,y,z,e,speed part, I think it is a really good PR. (Also it would solve the print finished deregistration problem, which is a huge +1)

(Sorry for the late response, I didn't noticed that I get a PR...)

**Comment by deadly667** [comment]
Well, I have no problem with removing x,y,z,e and speed axis. Personally, I dont find them useful for me too. 

But, maybe someone find them useful for correlation between some data. My idea was to have as much as possible data in prometheus so that we always can do some analytics. Something like Data lake for octoprint. And yes, you can always sum values in grafana if you want that kind of graph/number. 

Movement graphs looks like this example:
image

**Comment by tg44** [comment]
My problem with the x,y,z that these are positions. If you check in every 10 sec where is your x position, I think that data is useless... You either want it continuously, or you don't care at all, but snapshots from every 10s is more like a resource killer for me. I think too much data can be too much :D 

BTW as a sum I meant the total movement, which would be harder to measure I think, but that is an interesting statistic (for me at least, but probably could signal different wearoffs). Summing in grafana is not the same as absolute movement, bcs if you move your nozzle from -200 to +200 the grafana sum will be 0 but the movement is 400.

**Comment by deadly667** [comment]
Movement removed.

**Comment by tg44** [comment]
I merged it! Thank you!

I forgot one more thing :D Can you update the readme too?

**Pull request merged**
